random_seed: 123

data:
  num_samples: 3000

  validation_split: 0.33

  signal_length: 256
  signal_duration: 1

  amplitude_low: 10
  amplitude_high: 100

  frequency_low: 2
  frequency_high: 10

  phase_low: 0
  phase_high: 6.28

  relative_noise_std: 0.01

model:
  device: cuda
  batch_size: 128
  learning_rate: 3.0e-5

  num_epochs: 1000

  kernel_sizes:
    - 5
    - 5
  strides:
    - 2
    - 2

  hidden_channels:
    - 32
    - 64

  dilations: null

  paddings: null